const $=x=>document.getElementById(x);let img=null;
const grapes=["Riesling","Chardonnay","Sauvignon Blanc","Grauburgunder","Weißburgunder","Pinot Noir","Spätburgunder","Cabernet Sauvignon","Merlot","Syrah","Tempranillo","Sangiovese","Nebbiolo"];
const regions=[["Mosel","Deutschland"],["Rheingau","Deutschland"],["Pfalz","Deutschland"],["Nahe","Deutschland"],["Bordeaux","Frankreich"],["Burgund","Frankreich"],["Champagne","Frankreich"],["Rioja","Spanien"],["Ribera del Duero","Spanien"],["Toskana","Italien"],["Piemont","Italien"]];
const preds=["Kabinett","Spätlese","Auslese","Beerenauslese","Trockenbeerenauslese","Eiswein"];
const wineries=["Markus Molitor","Dr. Loosen","Joh. Jos. Prüm","Egon Müller","Dönnhoff","Robert Weil","Keller","Wittmann","Fritz Haag","Schloss Lieser","Clemens Busch"];
const n=s=>String(s||"").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[^a-z0-9]+/g," ");
function lev(a,b){a=n(a);b=n(b);let d=Array(b.length+1).fill(0).map((_,i)=>i);for(let i=1;i<=a.length;i++){let p=d;d=[i];for(let j=1;j<=b.length;j++)d[j]=Math.min(d[j-1]+1,p[j]+1,p[j-1]+(a[i-1]!=b[j-1]));}return 1-d[b.length]/Math.max(a.length,b.length,1)}
function contains(t,q){return n(t).includes(n(q))}
function canvas(b,mode){let s=Math.min(2,1800/b.width),w=Math.round(b.width*s),h=Math.round(b.height*s),c=document.createElement("canvas");c.width=w;c.height=h;let x=c.getContext("2d",{willReadFrequently:true});x.drawImage(b,0,0,w,h);let im=x.getImageData(0,0,w,h),d=im.data;for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];if(mode==1)g=(g-128)*1.6+128;if(mode==2)g=g>155?255:0;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
async function run(src,k){let r=await Tesseract.recognize(src,"deu+eng",{logger:m=>{if(m.status=="recognizing text")$("bar").style.width=(k*33+m.progress*33)+"%"}});return r.data.text||""}
function parse(texts){let t=texts.join("\n"),lines=t.split(/\n/).map(x=>x.trim()).filter(Boolean),o={};
let y=t.match(/\b(19[5-9]\d|20[0-3]\d)\b/);o.vintage=y?y[0]:"";
o.grapes=grapes.find(g=>contains(t,g)||lines.some(l=>lev(l,g)>.65))||"";
for(let [r,c] of regions)if(contains(t,r)||lines.some(l=>lev(l,r)>.7)){o.region=r;o.country=c;break}
o.predicate=preds.find(p=>contains(t,p)||lines.some(l=>lev(l,p)>.65))||"";
let best=["",0];for(let w of wineries)for(let l of lines){let s=lev(l,w);if(s>best[1])best=[w,s]}o.winery=best[1]>.48?best[0]:"";
if((contains(t,"erdener")||lines.some(l=>lev(l,"Erdener")>.5))&&(contains(t,"treppchen")||lines.some(l=>lev(l,"Treppchen")>.45)))o.appellation="Erdener Treppchen";else{o.appellation="";let pi=lines.findIndex(l=>preds.some(p=>contains(l,p)||lev(l,p)>.6));if(pi>0&&!/\d{4}/.test(lines[pi-1]))o.appellation=lines[pi-1]}
if(o.grapes=="Riesling"||["Chardonnay","Sauvignon Blanc","Grauburgunder","Weißburgunder"].includes(o.grapes))o.type="Weißwein";else if(o.grapes)o.type="Rotwein";
let a=t.match(/(\d{1,2}[.,]\d)\s*%?\s*(?:vol|alc)/i);o.alcohol=a?a[1].replace(".",","):"";return o}
async function load(f){if(!f)return;img=f;$("preview").src=URL.createObjectURL(f);$("preview").style.display="block";$("analyzeBtn").disabled=false}
$("cameraInput").onchange=e=>load(e.target.files[0]);$("galleryInput").onchange=e=>load(e.target.files[0]);
$("analyzeBtn").onclick=async()=>{if(!img)return;$("analyzeBtn").disabled=true;$("status").textContent="Foto wird in drei Varianten analysiert …";try{let b=await createImageBitmap(img),ts=[];for(let k=0;k<3;k++)ts.push(await run(canvas(b,k),k));$("ocrText").textContent=ts.map((x,i)=>"--- OCR "+(i+1)+" ---\n"+x).join("\n\n");let o=parse(ts);for(let k of ["winery","vintage","type","grapes","country","region","appellation","predicate","alcohol"])if(o[k])$(k).value=o[k];$("status").textContent="Mehrfach-OCR abgeschlossen. Bitte Felder prüfen.";$("bar").style.width="100%"}catch(e){$("status").textContent="Erkennung fehlgeschlagen. Bitte Foto erneut aufnehmen."}finally{$("analyzeBtn").disabled=false}};
const ids=["ean","winery","vintage","type","grapes","country","region","appellation","predicate","alcohol","size","qty","price","shelf","slot","notes"];
function data(){let o={};ids.forEach(i=>o[i]=$(i).value);return o}function all(){try{return JSON.parse(localStorage.winesV5||"[]")}catch{return[]}}function render(){let a=all();$("archive").innerHTML=a.map(w=>`<p><b>${w.winery||""} ${w.vintage||""}</b><br>${w.appellation||""} · ${w.grapes||""} · ${w.predicate||""}</p>`).join("")||"Noch keine Weine gespeichert."}
$("saveBtn").onclick=()=>{let a=all();a.unshift(data());localStorage.winesV5=JSON.stringify(a);render();$("status").textContent="Wein gespeichert."};$("clearBtn").onclick=()=>{ids.forEach(i=>$(i).value="");$("size").value="0,75";$("qty").value="1"};
$("csvBtn").onclick=()=>{let a=all(),q=v=>`"${String(v||"").replace(/"/g,'""')}"`,csv="\uFEFF"+ids.join(";")+"\n"+a.map(w=>ids.map(i=>q(w[i])).join(";")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),l=document.createElement("a");l.href=u;l.download="weinkeller-v5.csv";l.click()};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();